name: TestDeployment

on:
  workflow_dispatch:

jobs:
  Deploy-Sample-App:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create JavaDocs
        uses: Shynixn/jvm-docs-action@v1.0.0
        with:
          source-dirs: "sample-hello-world/src/main/java/com/github/shynixn/universe"
          target-dir: "docs/apidocs/java"
          doctype: "javaDocs"
          github-secret: ${{ secrets.GITHUB_TOKEN }}

      - name: Create KotlinDocs
        uses: Shynixn/jvm-docs-action@v1.0.0
        with:
          source-dirs: "sample-hello-world/src/main/kotlin"
          target-dir: "docs/apidocs/kotlin"
          doctype: "kotlinDocs"
          github-secret: ${{ secrets.GITHUB_TOKEN }}
